use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    Emitter, Manager, WindowEvent,
};

// Raw RGBA pixel data (32×32, 4 bytes per pixel) generated by scripts/create-icon.mjs
const TRAY_RUNNING: &[u8] = include_bytes!("../icons/tray-running.rgba");
const TRAY_IDLE: &[u8] = include_bytes!("../icons/tray-idle.rgba");
const TRAY_SIZE: u32 = 32;

#[tauri::command]
fn set_tray_icon(app: tauri::AppHandle, status: String) {
    let rgba: &[u8] = if status == "running" {
        TRAY_RUNNING
    } else {
        TRAY_IDLE
    };
    if let Some(tray) = app.tray_by_id("main") {
        let icon = Image::new(rgba, TRAY_SIZE, TRAY_SIZE);
        let _ = tray.set_icon(Some(icon));
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![set_tray_icon])
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            setup_tray(app)?;
            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running dr.titra");
}

fn setup_tray(app: &mut tauri::App) -> tauri::Result<()> {
    let toggle = MenuItem::with_id(app, "toggle", "Show / Hide", true, None::<&str>)?;
    let settings_item = MenuItem::with_id(app, "open-settings", "Settings", true, None::<&str>)?;
    let sep = PredefinedMenuItem::separator(app)?;
    let sep2 = PredefinedMenuItem::separator(app)?;
    let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&toggle, &sep, &settings_item, &sep2, &quit])?;

    let idle_icon = Image::new(TRAY_IDLE, TRAY_SIZE, TRAY_SIZE);

    TrayIconBuilder::with_id("main")
        .icon(idle_icon)
        .menu(&menu)
        .tooltip("dr.titra – Time Tracker")
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| match event.id.as_ref() {
            "toggle" => toggle_window(app),
            "open-settings" => {
                if let Some(w) = app.get_webview_window("main") {
                    let _ = w.show();
                    let _ = w.set_focus();
                }
                app.emit("open-settings", ()).ok();
            }
            "quit" => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                toggle_window(tray.app_handle());
            }
        })
        .build(app)?;

    Ok(())
}

fn toggle_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        if window.is_visible().unwrap_or(false) {
            let _ = window.hide();
        } else {
            let _ = window.show();
            let _ = window.set_focus();
        }
    }
}
